// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/session-report/Current.tsx": () => import("../components/mockups/session-report/Current.tsx"),
  "./components/mockups/session-report/MeasuredSessionReport.tsx": () => import("../components/mockups/session-report/MeasuredSessionReport.tsx")
};
